apiVersion: v1
kind: Template
metadata:
  name: wordpress-template
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: claim1
      namespace: wordpress
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs-storage
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: db
      namespace: wordpress
    spec:
      selector:
        app: db
      replicas: 1
      template:
        metadata:
          labels:
            app: db
        spec:
          volumes:
            - name: db
              persistentVolumeClaim:
                claimName: claim1
          containers:
            - name: db
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret-wordpress
                      key: MYSQL_ROOT_PASSWORD
                - name: MYSQL_DATABASE
                  value: wordpress
                - name: MYSQL_USER
                  value: wordpress
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret-wordpress
                      key: MYSQL_PASSWORD
              ports:
                - containerPort: 3306
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: db
                  mountPath: /var/lib/mysql
              image: 'mysql:5.7'
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: wordpress
      namespace: wordpress
    spec:
      selector:
        app: wordpress
      replicas: 1
      template:
        metadata:
          labels:
            app: wordpress
        spec:
          containers:
            - name: wordpress
              env:
                - name: WORDPRESS_DB_HOST
                  value: 'db:3306'
                - name: WORDPRESS_DB_USER
                  value: wordpress
                - name: WORDPRESS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret-wordpress
                      key: WORDPRESS_DB_PASSWORD
              ports:
                - containerPort: 8080
                  protocol: TCP
              imagePullPolicy: Always
              image: 'image-registry.openshift-image-registry.svc:5000/wordpress/wordpress'
  - kind: Service
    apiVersion: v1
    metadata:
      name: db
      namespace: wordpress
    spec:
      ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
      selector:
        app: db
  - kind: Service
    apiVersion: v1
    metadata:
      name: wordpress
      namespace: wordpress
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: wordpress
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: wordpress
      namespace: wordpress
    spec:
      host: wordpress-wordpress.apps.lab.okd.local
      to:
        kind: Service
        name: wordpress
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
