apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: 'wordpress'
  namespace: wordp
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build
  namespace: wordp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'wordpress:latest'
  strategy:
    type: Docker
    dockerStrategy:
  source:
    type: Git
    git:
      uri: 'https://github.com/mehdi-wsc/apalia-Wp.git'
