
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
